### ISSUE TITLE
content format issue

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-kevin-kears/dustybuns#3]
issue: content needs to be formatted to match original
page: about us

how you have it:
![screen shot 2016-03-25 at 8 42 50 am](https://cloud.githubusercontent.com/assets/7436666/14047580/e25cd81c-f265-11e5-8cb6-3f8dba8238dc.png)

how it should be:
![screen shot 2016-03-25 at 8 42 38 am](https://cloud.githubusercontent.com/assets/7436666/14047581/e5f0a54e-f265-11e5-81a0-e1d9e81cdb11.png)

**Comment by geekwise-kevin-kears** [comment]
http://geekwise-kevin-kears.github.io/dustybuns/about.html

finally got to it sam

**Comment by Sramos9191** [comment]
@geekwise-kevin-kears it's looking good!
